@isTest
public class UsersTest {
    @isTest
    public static void testCoverage() {
        Users.vh24Lv();
        Users.vh24Diesel();
        Users.vh24Darlehen();
        Users.vh24pixel();
        Users.vr24();
        Users.vr24diesel();
        Users.potentialCheck();
        Users.consultant();
        Users.clerkAppeal();
        Users.CarmenHornung();
        Users.MariaGorzna();
        Users.cllbClerk();
        Users.JCLegal();
        Users.JHLegal();
        Users.JHeinrichLegal();
        Users.JAndCLegal();
        Users.kainzLegal();
        Users.krutischLegal();
        Users.lachmairLegal();
        Users.legal21();
        Users.cllbLegal();
        Users.NinaHoyer();
    }
}